---
abstract: 'Dump strings of characters (or bytes) for printing and debugging'
author:
  - 'Nick Patch <patch@cpan.org>'
build_requires:
  Test::More: 0.82
  Test::Warn: 0
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: String-Dump
provides:
  String::Dump:
    file: lib/String/Dump.pm
    version: 0.07
requires:
  Getopt::Lucid: 0
  parent: 0
  perl: v5.6.0
resources:
  bugtracker: https://github.com/patch/string-dump-pm5/issues
  homepage: https://github.com/patch/string-dump-pm5
  license: http://dev.perl.org/licenses/
  repository: git://github.com/patch/string-dump-pm5.git
version: 0.07
